Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1072, in _find_spec
AttributeError: '_SixMetaPathImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antoine/dev/python/packages/timeseries/pyaf/tests/bugs/run_benchmark_M4Comp_ECONOMICS_ECON1151_18.py", line 11, in <module>
    tester = mcomp.cMComp_Tester(tsds.load_M4_comp(lType) , "M4_COMP_" + lType);
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/dev/python/packages/timeseries/pyaf/pyaf/Bench/TS_datasets.py", line 699, in load_M4_comp
    df_full = pd.read_csv(trainfile, sep=',', header=0, engine='python', compression='gzip');
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/antoine/.local/lib/python3.11/site-packages/pandas/io/common.py", line 719, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/.local/lib/python3.11/site-packages/pandas/io/common.py", line 1181, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/.local/lib/python3.11/site-packages/pandas/io/common.py", line 1196, in _get_binary_io_classes
    zstd = import_optional_dependency("zstandard", errors="ignore")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1138, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1074, in _find_spec
  File "<frozen importlib._bootstrap>", line 1047, in _find_spec_legacy
ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
EXECUTION_TIME_DETAIL = {'CMD':'timeout 480 python tests/bugs/run_benchmark_M4Comp_ECONOMICS_ECON1151_18.py', 'ElapsedTimeSecs':(0.63, 0.08, 0.55), 'MAX_MEM_KB':71776, 'CPU_PRCNT':'99%', 'FILES_IN':0, 'FILES_OUT':8, 'EXIT_STATUS':1}
